from queries.db import *
from queries.Deficiencia import *
from queries.BucketAdmision import *
from queries.BucketExamenPrueba import *
from queries.Institucion import *
from queries.Municipio import *
from queries.Departamento import *
from queries.Pais import *
from queries.QueryExecutor import *
