from queries.db import *
from queries.Deficiencia import *
from queries.BucketAdmision import *
from queries.BucketExamenPrueba import *
from queries.Institucion import *
from queries.Municipio import *
from queries.Departamento import *
from queries.Pais import *
from queries.QueryExecutor import *
from queries.BucketFeedback import *
from queries.DeficienciaFeedback import *
from queries.Feedback import *
from queries.EtiquetaFeedback import *
from queries.TemaFeedback import *
from queries.SeccionFeedback import *
from queries.Bucket import *
from queries.ReporteResumen import *
from queries.FilaReporte import *
from queries.Reporte import *
